"""The installed A1X as one MuJoCo model: the arm, the table and the tool frame.

The arm is `assets/a1x.xml`, generated by `sim/urdf2mjcf.py` from the vendor URDF
(the same generator as `sim/a1x.xml`; only the mesh directory differs). The rest
of the installation is fixed, not a scene:

  * base_link at the origin, x forward over the table, z up;
  * the table top is the plane z = 0 of that frame;
  * one end effector, whose tool frame is a fixed transform from arm_link6.

Joint angles everywhere in this package are radians as the model and the wire
use them (0x050 p_des, 0x052 position): no offsets, no degrees.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Iterable, Sequence, Tuple, Union

import mujoco
import numpy as np

ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets")
MJCF = os.path.join(ASSETS, "a1x.xml")

JOINTS = tuple(f"arm_joint{i}" for i in range(1, 7))
FINGERS = ("gripper_finger_joint1", "gripper_finger_joint2")
LAST_LINK = "arm_link6"
BASE = "base_link"
TOOL_SITE = "tool"
TABLE = "table"


@dataclass(frozen=True)
class Tool:
    """Tool centre point as a fixed transform from arm_link6: position [m] and quaternion (w, x, y, z).

    The default is the A1X gripper: gripper_link sits 0.08165 m out along x of arm_link6, and the
    point between the parallel finger plates is 0.045 m further (the `tcp` site of the model).
    x of the tool frame is the approach direction, y the jaw closing axis.
    """

    pos: Tuple[float, float, float] = (0.12665, 0.0, 0.0)
    quat: Tuple[float, float, float, float] = (1.0, 0.0, 0.0, 0.0)

    def matrix(self) -> np.ndarray:
        T = np.eye(4)
        R = np.zeros(9)
        q = np.asarray(self.quat, float)
        mujoco.mju_quat2Mat(R, q / np.linalg.norm(q))
        T[:3, :3] = R.reshape(3, 3)
        T[:3, 3] = self.pos
        return T


GRIPPER = Tool()


@dataclass(frozen=True)
class Box:
    """Obstacle: axis-aligned box in the base frame, centre and half-sizes [m]."""

    center: Tuple[float, float, float]
    half: Tuple[float, float, float]
    name: str = ""


@dataclass(frozen=True)
class Sphere:
    """Obstacle: sphere in the base frame, centre and radius [m]."""

    center: Tuple[float, float, float]
    radius: float
    name: str = ""


Obstacle = Union[Box, Sphere]


def _as_obstacles(obstacles: Iterable[Obstacle]) -> Tuple[Obstacle, ...]:
    out = []
    for o in obstacles or ():
        if isinstance(o, Box):
            out.append(Box(tuple(float(v) for v in o.center), tuple(float(v) for v in o.half), o.name))
        elif isinstance(o, Sphere):
            out.append(Sphere(tuple(float(v) for v in o.center), float(o.radius), o.name))
        else:
            raise TypeError(f"obstacle must be Box or Sphere, got {type(o).__name__}")
    return tuple(out)


def build(tool: Tool = GRIPPER, obstacles: Sequence[Obstacle] = ()) -> mujoco.MjModel:
    """Compile the installation: arm + table plane + tool site (+ obstacles, static, named by kind)."""
    spec = mujoco.MjSpec.from_file(MJCF)
    world = spec.worldbody

    table = world.add_geom()
    table.name = TABLE
    table.type = mujoco.mjtGeom.mjGEOM_PLANE
    table.size = [0.0, 0.0, 0.05]                # 0 = infinite plane

    link6 = spec.body(LAST_LINK)
    site = link6.add_site()
    site.name = TOOL_SITE
    site.pos = list(tool.pos)
    site.quat = list(tool.quat)

    for k, o in enumerate(_as_obstacles(obstacles)):
        g = world.add_geom()
        g.name = f"obstacle{k}" + (f" {o.name}" if o.name else "")
        g.pos = list(o.center)
        if isinstance(o, Box):
            g.type = mujoco.mjtGeom.mjGEOM_BOX
            g.size = list(o.half)
        else:
            g.type = mujoco.mjtGeom.mjGEOM_SPHERE
            g.size = [o.radius, 0.0, 0.0]
    return spec.compile()


@dataclass
class Indices:
    """Addresses of the arm joints and the tool site in a compiled model."""

    qadr: np.ndarray
    dadr: np.ndarray
    lo: np.ndarray
    hi: np.ndarray
    finger_qadr: np.ndarray
    site: int
    base: int
    home: np.ndarray = field(default_factory=lambda: np.zeros(6))
    finger_home: np.ndarray = field(default_factory=lambda: np.zeros(2))


def indices(model: mujoco.MjModel) -> Indices:
    ids = [model.joint(n).id for n in JOINTS]
    fids = [model.joint(n).id for n in FINGERS]
    qadr = np.array([model.jnt_qposadr[i] for i in ids])
    fadr = np.array([model.jnt_qposadr[i] for i in fids])
    key = model.key("home").id
    kq = model.key_qpos[key]
    return Indices(
        qadr=qadr,
        dadr=np.array([model.jnt_dofadr[i] for i in ids]),
        lo=model.jnt_range[ids, 0].copy(),
        hi=model.jnt_range[ids, 1].copy(),
        finger_qadr=fadr,
        site=model.site(TOOL_SITE).id,
        base=model.body(BASE).id,
        home=kq[qadr].copy(),
        finger_home=kq[fadr].copy(),
    )


def limits() -> Tuple[np.ndarray, np.ndarray]:
    """Joint limits of arm_joint1..6 from the model [rad]: (lo, hi)."""
    ix = indices(build())
    return ix.lo, ix.hi
